mindsdb/mindsdb-docs

mindsdb-docs/docs/comparisons/ComparsionWithOtherLibraries.md

This PR improves the examples and fix the issues. Now, all of the examples are working. The scikit and ludwig examples are working now using the home_rentals dataset. Also, mindsdb example is improved and simplified. The preprocessing part is removed since the parsing is in each example. Note that Tensorflow example works but with random data for now, and Travis is successfull even it displays failed status.

Improve comparisons

---

README.md
mindsdb-docs/docs/GoogleColab.md
mindsdb-docs/docs/Installing.md
mindsdb-docs/docs/JupyterNotebook.md
mindsdb-docs/docs/PredictorInterface.md
mindsdb-docs/mkdocs.yml
mindsdb-docs/site/server/InstallServer/index.html

Fixed a couple of typos and added mkdocs-material to the installation procedure

Typo fixes

---

mindsdb-docs/docs/scout/Introduction.md

Fixes #71
Changed 0.0.0.0 to localhost

Changed 0.0.0.0 to localhost

---

mindsdb-docs/docs/Installing.md

Fixes https://github.com/mindsdb/mindsdb/issues/774
- Added installation guide using virtualenv 
- Added installation guide using host environment

Add virtualenv in MindsDB installation and fix documentation

---

mindsdb-docs/docs/Installing.md

Fixes #784
- added detailed instructions on how to install virtual env and mindsdb in Windows
- tested and verified through Windows

added Install in Windows section in standard installation docs

---

mindsdb-docs/docs/databases/MariaDB.md

Fixes #786
changed config_version from 1.1 to 1.3
Ticket: https://github.com/mindsdb/mindsdb/issues/786

Update the MariaDB configuration example

---

mindsdb-docs/docs/Installing.md

I have changed the documentation where it says python version 3.7 to 3.6
Fixes #
- Changed the version to 3.6 from 3.7

Changed 3.7 to 3.6 Python version

---

mindsdb-docs/docs/Installing.md

Fixes #89 
Please, add the label "hacktoberfest-accepted" in order to this PR be valid for hacktoberfest. I'd be thankful.

fix: Fix required python version to >=3.6

---

mindsdb-docs/docs/tutorials/Timeseries.md
mindsdb-docs/mkdocs.yml

- Moves Timeseries page down in the index
- Updates nr_prediction argument

Move Timeseries.md, update nr_predictions arg

---

.travis.yml

Fixes #
Added missing plugin in Travis.yml

Fix travis #78

---

mindsdb-docs/docs/Installing.md

Fix issue mindsdb#817 Add new installation section in windows in mindsb documentation.
Fixes mindsdb#817 (https://github.com/mindsdb/mindsdb/issues/817)
- Add installation section on windows using installer.

Add new installation section mindsdb#817

---

mindsdb-docs/docs/lightwood/info.md

Fixes #821 from mindsdb issue
-  Added a separate section for Installation on windows
-  Added an example of installation on a Virtual Environment
[Updated info.md](https://github.com/yash2189/mindsdb-docs/blob/doc-installation/mindsdb-docs/docs/lightwood/info.md)

doc:Updated Lightwood installation docs 

---

mindsdb-docs/docs/scout/Introduction.md

Changed the default Scout URL in docs

---

mindsdb-docs/docs/Installing.md

Fixes #832 from mindsdb issues
-  Updated the mindsdb Server docs by removing the `/static` path and the message example.
Please find the updated file [here](https://github.com/yash2189/mindsdb-docs/blob/fix-%23832/mindsdb-docs/docs/Installing.md)

doc: Updated mindsdb server docs

---

README.md

Update the Travis CI badge to point to .com in README docs.
https://github.com/mindsdb/mindsdb/issues/848
Fixes #
- Update README docs to point to .com

Fix issue mindsdb#848

---

mindsdb-docs/docs/databases/tutorials/AiTablesInPostgreSQL.md

Fixes #
- Fix https://github.com/mindsdb/mindsdb/issues/856 
- Also found images links were wrong and actually thats why the images in the md files were not loading, so fixing that too

Fixing md issue 856 and fixing images to load

---

mindsdb-docs/docs/databases/tutorials/AiTablesInPostgreSQL.md

Fixes #857 from mindsdb issues
- Changes have been made under `mindsdb-docs/docs/databases/tutorials/AiTablesInPostgreSQL.md`
- Previously, the PostgreSQL code was not properly formatted. This the [previous](https://github.com/yash2189/mindsdb-docs/blob/master/mindsdb-docs/docs/databases/tutorials/AiTablesInPostgreSQL.md) file.
- Added a `sql` block for the same , find the new file [here](https://github.com/yash2189/mindsdb-docs/blob/fix%23857/mindsdb-docs/docs/databases/tutorials/AiTablesInPostgreSQL.md)

Fixed Display of SQL Query in the docs

---

mindsdb-docs/docs/databases/tutorials/AiTablesInMySQL.md

Fixes #859 from mindsdb issues
- Changes have been made under `mindsdb-docs/docs/databases/tutorials/AiTablesInMySQL.md`
- Previously, the MySQL code was not properly formatted. This the [previous](https://github.com/yash2189/mindsdb-docs/blob/master/mindsdb-docs/docs/databases/tutorials/AiTablesInMySQL.md) file.
- Added a `sql` block for the same , find the new file [here](https://github.com/yash2189/mindsdb-docs/blob/fix%23859/mindsdb-docs/docs/databases/tutorials/AiTablesInMySQL.md)

docs :Formatted the SQL query in AI Tables docs

---

mindsdb-docs/docs/Installing.md

Fixes #861 of mindsdb issues
- Changes have been made under `mindsdb-docs/docs/Installing.md`
- Previously, there was a section for `Install on Windows using MindsDB installers`. The old file can be found [here](https://github.com/mindsdb/mindsdb-docs/blob/master/mindsdb-docs/docs/Installing.md#install-using-virtual-environment)
- This section has been removed . Updated file [here](https://github.com/yash2189/mindsdb-docs/blob/fix%23861/mindsdb-docs/docs/Installing.md)

docs : Updated mindsdb installation docs

---

mindsdb-docs/docs/databases/tutorials/AiTablesInPostgreSQL.md

Fixes #865 from mindsdb issues
- This PR is a documentation improvement for pointing the PostgreSQL download link to its proper download page.
- Changes made under `/docs/databases/tutorials/AiTablesInPostgreSQL.md`
Changes can be found [here](https://github.com/yash2189/mindsdb-docs/blob/fix%23865/mindsdb-docs/docs/databases/tutorials/AiTablesInPostgreSQL.md)

docs : Updated docs for AiTablesInPostgreSQL.md

---

requirements.txt

- Added requirements.txt with the dependencies needed to run the docs locally.

Added requirements.txt to install the dependencies for the docs.

---

README.md
mindsdb-docs/mkdocs.yml

1. Removed the reference of google analytics from mkdocs.yml
2. Corrected a type in README.md
-

Removing Google Analytics from docs

---

README.md
mindsdb-docs/docs/InsideMindsDB.md
mindsdb-docs/docs/Installing.md
mindsdb-docs/docs/databases/MySQL.md
mindsdb-docs/docs/integrations/UseMindsDBinSage.md
mindsdb-docs/docs/lightwood/API.md
mindsdb-docs/docs/scout/Introduction.md
mindsdb-docs/docs/scout/Predictors.md
mindsdb-docs/docs/scout/Query.md
mindsdb-docs/docs/tutorials/CreditScoring.md
mindsdb-docs/docs/tutorials/CustomerLifetimeValue.md
mindsdb-docs/docs/tutorials/FraudDetection.md
mindsdb-docs/docs/tutorials/HotelBooking.md
mindsdb-docs/docs/tutorials/MedicalDiagnosis.md
mindsdb-docs/docs/tutorials/PatientHealthOutcomes.md
mindsdb-docs/docs/tutorials/PredictiveMaintenance.md

Updating Document issues

---

mindsdb-docs/docs/tutorials/Timeseries.md

Updated docs for: https://github.com/mindsdb/mindsdb_native/pull/242

Updated timeseries docs

---

mindsdb-docs/docs/Installing.md

Minor copyedits to Installing

---

.travis.yml
requirements.txt

- add mkdocs-redirects to fix Travis CI error
- Error message: `ERROR   -  Config value: 'plugins'. Error: The "redirects" plugin is not installed`

Fix travis error

---

mindsdb-docs/docs/tutorials/mariadb.md

Fix load data query

---

mindsdb-docs/docs/model/mariadb.md
mindsdb-docs/docs/model/mongodb.md
mindsdb-docs/docs/model/mysql.md
mindsdb-docs/docs/model/postgresql.md

Add timeseries example to training docs for each database (except, mss done earlier)

---

mindsdb-docs/docs/datasources/mongodb.md

Update mongo API docs
